### ISSUE TITLE
V5: MerchantReference is not returned in PaymentDetailsResponse

### ISSUE THREAD

**Issue by roybos** [Adyen/adyen-go-api-library#104]
**Describe the bug**
MerchantReference is not returned in `checkout.PaymentDetailsResponse` after successful payment

**To Reproduce**
1. Start a creditcard payment with 3DS2 (I used mastercard 5454 5454 5454 5454 expiration: 03/30 CVC: 737)
2. When you do the POST request for 3DS2 with the `details.threeDSResult` from the frontend (the result of the challenge) and you put this in `checkout.DetailsRequest`, you get a valid response with ResultCode is Authorised and PSPReference is filled with an ID, but MerchantReference is empty.

**Expected behavior**
In V3 we get MerchantReference back after a successful payment with a creditcard with 3DS2, so we also expect this valiie to be filled in V5.

**Additional context**
I noticed in Adyen portal that the Payments overview for this payment is reporting the wrong API version: adyen-go-api-library:4.0.0, but I am using 5.0.0. V4 was even more broken, like reported in [https://github.com/Adyen/adyen-go-api-library/issues/93](https://github.com/Adyen/adyen-go-api-library/issues/93)

**Comment by deepu105** [comment]
Hi @roybos thanks for the issue report.

here is a PR that should fix the version issue and i'm looking into the MerchantReference issue. Will release a patch soon

**Comment by deepu105** [comment]
@roybos just released v5.0.1 that fixes the lib version and many other improvements. For the merchant reference issue, its a backend issue and will be fixed in the REST API directly

**Comment by roybos** [comment]
Thanks for the fast fix! 👍 
Any idea when the merchant reference will be fixed in the REST API?

**Comment by deepu105** [comment]
@roybos we are prioritizing it but unfortunately I dont have a timeline yet. i'll ping you and inform you when its fixed
