### ISSUE TITLE
Checkout modification support

### ISSUE THREAD

**Issue by leonidasv** [Adyen/adyen-go-api-library#116]
**Is your feature request related to a problem? Please describe.**
Sorry if I'm missing something, but I haven't found any of the [Checkout Modification endpoints](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments/{paymentPspReference}/captures) in this library. They seem to be implemented for other languages/frameworks (eg: [node](https://github.com/Adyen/adyen-node-api-library/blob/ef94f38cc7d887c1d903c10470fbb276188258f8/src/services/resource/modification/captures.ts)). 

**Describe the solution you'd like**
A clear path for requesting modifications for "new integrations".

**Describe alternatives you've considered**
...implementing it myself?

**Additional context**
N/A.

**Comment by jillingk** [comment]
Hi @leonidasv,

Super big apologies for the delayed response. Just wanted to let you know that since our latest release these issues have been resolved and the modification endpoints have been added.

Best, Jilling
Adyen
