### ISSUE TITLE
[PW-8057] PaymentResponse does not work on the FraudResult field

### ISSUE THREAD

**Issue by yunpengn** [Adyen/adyen-go-api-library#120]
**Describe the bug**

This Go library's definition on the `fraudResult` field of latest `/payments` endpoint is wrong. In fact, each `FraudCheckResult` is nested rather than a flat array.

The actual JSON format is:

```
"fraudResult": {
    "accountScore": 90,
    "results": [
        {
            "FraudCheckResult": {
                "accountScore": 0,
                "checkId": 2,
                "name": "CardChunkUsage"
            }
        },
    ...
    ]
}
```

Current definition in this library:

```
type FraudResult struct {
	// The total fraud score generated by the risk checks.
	AccountScore int32 `json:"accountScore"`
	// The result of the individual risk checks.
	Results *[]FraudCheckResult `json:"results,omitempty"`
}

type FraudCheckResult struct {
	// The fraud score generated by the risk check.
	AccountScore int32 `json:"accountScore"`
	// The ID of the risk check.
	CheckId int32 `json:"checkId"`
	// The name of the risk check.
	Name string `json:"name"`
}
```

Correct implementation should be:

```
type FraudResult struct {
	// The total fraud score generated by the risk checks.
	AccountScore int32 `json:"accountScore"`
	// The result of the individual risk checks.
	Results *[]FraudCheckResultContainer `json:"results,omitempty"`
}

type FraudCheckResultContainer struct {
         FraudCheckResult *FraudCheckResult `json:"FraudCheckResult,omitempty"`
}

type FraudCheckResult struct {
	// The fraud score generated by the risk check.
	AccountScore int32 `json:"accountScore"`
	// The ID of the risk check.
	CheckId int32 `json:"checkId"`
	// The name of the risk check.
	Name string `json:"name"`
}
```

**To Reproduce**

To reproduce, make a call to `/payments` endpoint (with fraud-related additional data enabled in Adyen CA), and you will find out the elements inside `results` array under `fraudResult` field in API response could not be unmarshalled correctly.

**Expected behavior**

Should fix the implementation, the Java library implements it correctly, see https://github.com/Adyen/adyen-java-api-library/blob/develop/src/main/java/com/adyen/model/FraudCheckResultContainer.java

**Comment by michaelpaul** [comment]
Hey @yunpengn, 

Thanks for reporting this issue! It has been fixed in the [v7 release](https://github.com/Adyen/adyen-go-api-library/releases/tag/v7.0.0). The new [models](https://github.com/Adyen/adyen-go-api-library/blob/bf7ea8b5f35843c8fe2ea60c6e2f44fee0750242/src/checkout/model_payment_response.go#L28) reflect server responses correctly now.
