### ISSUE TITLE
Schema described in API documentation does not match model files

### ISSUE THREAD

**Issue by rlcooper46** [Adyen/adyen-go-api-library#135]
**Describe the bug**
Missing schema in model files

The schema specified here: https://docs.adyen.com/api-explorer/#/NotificationService/v6/post/ACCOUNT_HOLDER_CREATED__reqParam_content-verification

the model for this object does not match the expected output:
https://github.com/Adyen/adyen-go-api-library/blob/a06e2c765ed9a6c22433bbb75d05a78eba4b397c/src/platformsnotificationevents/model_kyc_verification_result.go#L19

Ideally, these should match so the model is fully usable.

**Comment by michaelpaul** [comment]
Hello @rlcooper46, these `src/platforms*` API's are **deprecated** and shall be removed soon. Please migrate to the new [Adyen For Platforms](https://docs.adyen.com/marketplaces-and-platforms).
