### ISSUE TITLE
Remove unused models

### ISSUE THREAD

**Issue by gcatanese** [Adyen/adyen-go-api-library#143]
As the OpenAPI specs evolve few models are removed from the specification but still left (and unused) in the code

**Describe the solution you'd like**
Remove unused code/model: LianLianPayDetails, ResponseAdditionalDataDeliveryAddress, etc.. (perform an analysis to identify models no longer in used)

**Describe alternatives you've considered**
The only alternative is to leave those unused files

**Comment by michaelpaul** [comment]
Hey @gcatanese, Good point! We've performed this cleanup while doing the v7 upgrade.
