### ISSUE TITLE
[PW-7072] Checkout API supported version

### ISSUE THREAD

**Issue by strobil** [Adyen/adyen-go-api-library#153]
Hi, according to the [docs](https://docs.adyen.com/risk-management/dynamic-3d-secure), i can use [authenticationData.attemptAuthentication](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/payments__reqParam_authenticationData-attemptAuthentication) parameter in payment request.

I have tried to add this params to my payment request, but i've got an error: "Structure of PaymentRequest contains the following unknown fields: [authenticationData] (validation: 702)"
 
This parameters requires Checkout API v69 (which is supported by this library according to README.md file), but, in the source code i found that client uses v68 api.
https://github.com/Adyen/adyen-go-api-library/blob/75014e9d9c3705ded2f8ee16bd933f626fadf4a9/src/adyen/api.go#L51

Could you please check this? What is the actually supported version for Checkout API?
Thank you!

**Comment by jillingk** [comment]
Hi @strobil, 

Thank you for reaching out to us with this issue. You're right in that indeed we still use version 68 for the checkout api in this library. I have created an internal ticket to up this to v69 and add the newer models for this version. You're also always welcome to contribute and open an PR yourself!

Best, Jilling
Adyen

**Comment by strobil** [comment]
@jillingk just a quick look at the models definitions shows that they are already generated for API v69,
so I've submitted a PR #154 which should fix this issue

thanks!

**Comment by jillingk** [comment]
Hey @strobil,

You're right, however what worries me a bit is that not quite all the models are v69. Presumably this would be the case because some models did not change over the different versions, but I'm quickly going to double check this and come back to you.

Best, Jilling
Adyen

**Comment by gcatanese** [comment]
@strobil This should be addressed now with the changes in PR #154. I can verify the fix with a unit test (which I will add/push later), can you please confirm on your side? Thanks

**Comment by strobil** [comment]
> @strobil This should be addressed now with the changes in PR #154. I can verify the fix with a unit test (which I will add/push later), can you please confirm on your side? Thanks

Hi. Now I can confirm that all works as I expect. I've tested a new [parameter](https://docs.adyen.com/api-explorer-beta/Checkout/69/post/payments#request-authenticationData-threeDSRequestData-nativeThreeDS) which has been introduced in Checkout API v69.
Could you please make a new tagged release?

**Comment by gcatanese** [comment]
@strobil v6.0.1 is released
