### ISSUE TITLE
Mask X-Api-Key Prefix On Debug Printout

### ISSUE THREAD

**Issue by wonderstim** [Adyen/adyen-go-api-library#244]
**Is your feature request related to a problem? Please describe.**
prevent API keys from being logged

**Describe the solution you'd like**
When running in debug the X-Api-Key should print with all but the last N characters *-masked.

**Describe alternatives you've considered**
Redirecting log output (if made configurable) helps but does not solve the problem when debug mode might need to be used in a sensitive pre-production environment.

**Additional context**
Quick and dirty solution:

```
// CallAPI do the Request.
func (c *Client) CallAPI(request *http.Request) (*http.Response, error) {
    originalKey := request.Header.Get("X-Api-Key")
	if c.Cfg.Debug {
        if len(request.Header.Get("X-Api-Key")) > 10 {
            cutPoint := len(request.Header.Get("X-Api-Key")) - 10
            maskedKey := strings.Repeat("*", cutPoint) + request.Header.Get("X-Api-Key")[cutPoint:]
            request.Header.Set("X-Api-Key", maskedKey)
        }
		dump, err := httputil.DumpRequestOut(request, true)
		if err != nil {
			return nil, err
		}
		log.Printf("\n%s\n", string(dump))
	}
    request.Header.Set("X-Api-Key", originalKey)
.
.
.
}
	```

**Comment by michaelpaul** [comment]
Hello @wonderstim, thanks for raising this issue. It looks like a good improvement that can be incorporated soon.
