### ISSUE TITLE
Panic In Response Handling For 504 Gateway Timeout

### ISSUE THREAD

**Issue by wonderstim** [Adyen/adyen-go-api-library#246]
**Describe the bug**
When creating Balance Accounts, a 504 Gateway Timeout causes the SDK to throw a panic. Specifically, `api_balance_accounts.go` line 71 which reads `if httpRes.StatusCode == 400 {` after failing to check is `httpRes` is nil or if `err` is not nil.

**To Reproduce**
Simulate a 504 gateway timeout from this endpoint. Currently we are receiving as much due to an Adyen outage in our test environment.

**Expected behavior**
The SDK should gracefully return an error.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by michaelpaul** [comment]
Thanks for reporting this error @wonderstim! A fix will be released soon.
