### ISSUE TITLE
Bancontact payment method on last lib versions

### ISSUE THREAD

**Issue by zaitera** [Adyen/adyen-go-api-library#282]
**Describe the bug**
CheckoutPaymentMethod does not have any option for `bcmc` (bancontact)

**To Reproduce**
1. Use the frontend of [adyen web](https://github.com/Adyen/adyen-web) on version 5.55.1
2. Use this adyen golang lib 8.1.0
3. Use an environment that has bancontact card enabled
4. Use auto parsing from payment data from [adyen web](https://github.com/Adyen/adyen-web) to a PaymentRequest it will work for other payment methods and fail on bcmc because CheckoutPaymentMethod has no option for bancontact.

**Expected behavior**
**CheckoutPaymentMethod(s) shall have an option of bcmc also, like the tens of other payment methods that are there**

**Screenshots**
Hereby two screenshots of how these values of bcmc used to look like on previous versions of [adyen web](https://github.com/Adyen/adyen-web) (scheme) and how it looks now on the last versions of both golang lib and web (bcmc):
<img width="198" alt="image" src="https://github.com/Adyen/adyen-go-api-library/assets/19367012/8b075d6d-3801-475c-847f-626b1a1dee34">
<img width="181" alt="image" src="https://github.com/Adyen/adyen-go-api-library/assets/19367012/2dfa63ed-fcb8-4949-aa86-6cd3bd8af167">
These are by selecting the same payment method on both occasions

**Desktop (please complete the following information):**
 - Chrome

**Comment by zaitera** [comment]
@michaelpaul

**Comment by wboereboom** [comment]
Hi @zaitera ,

Thanks for raising this issue.
We are currently working on a fix for this in our API spec. After this fix passed review it will automatically be included in the next release of the library.
Thank you for your patience, and apologies for any delay this might've caused.

Kind Regards,
Wouter
Adyen

**Comment by zaitera** [comment]
@AlexandrosMor @gcatanese @wboereboom @michaelpaul @jillingk
Hello, 
thanks for the release v9, we have been waiting for it for a while now.
I just wanna raise a problem here, this release is not updatable/usable because although the number is 9.0.0, it still uses v8 in the module path.
Related to this:
![image](https://github.com/Adyen/adyen-go-api-library/assets/19367012/2a371fd3-e859-4ad6-8943-76f2f8e9a5e4)

**Comment by zaitera** [comment]
result of that command: 
![image](https://github.com/Adyen/adyen-go-api-library/assets/19367012/2188cc0f-689d-4add-9154-242f98fe0eb8)

**Comment by jillingk** [comment]
Hi @zaitera,

Thanks for letting us know, we completely forgot to retag that one. Just manually rereleased v9, you should be able to retrieve it correctly now. Apologies for the troubles.

Best, Jilling
Adyen
