### ISSUE TITLE
Major version go module mismatch

### ISSUE THREAD

**Issue by compilersh** [Adyen/adyen-go-api-library#335]
**Describe the bug**
Your newest version (to date) describes installation process as:
`go get github.com/adyen/adyen-go-api-library/v9@v10.3.0`
This results in an error code:
`go: github.com/adyen/adyen-go-api-library/v9@v10.3.0: invalid version: module path includes a major version suffix, so major version must match`

**To Reproduce**
1. Initialize a new project
2. follow instructions on installing the latest Adyen library version

**Expected behavior**
Adyen should have been installed as a dependency

**Actual Behavior**
Adyen is rejected since the module version does not match the major version

**Additional context**
Update your module (v9) to (v10)

**Workaround**
go get with commit hash pointing to v10.3.0 to omit the major version code:
```
go get github.com/adyen/adyen-go-api-library/v9@f3e8c04
```

**Comment by wboereboom** [comment]
Hey @compilersh ,

I'm sorry this happened. 
This occurred due to a gap in our automation process that somehow slipped through the cracks.
We fixed and re-released the library in #337.

Kind Regards,
Wouter
Adyen
