### ISSUE TITLE
v4:  Actions returned from sdk are null where the api does return a value (checkout.PaymentResponseActionOneOf is nil)

### ISSUE THREAD

**Issue by steffenmllr** [Adyen/adyen-go-api-library#93]
**Describe the bug**

`client.Checkout.Payments(req)` returns a `nil` interface (`PaymentResponseActionOneOfInterface`) for actions when it api returns something. Either `PaymentResponseActionOneOfInterface` does not correctly get attached or I'm doing it wrong.
When is try to serialize the `res.Action`, it's always null. Debugging it also returns a nil interface.

```
(*checkout.PaymentResponseActionOneOf)(0xc0004a2530)({
 PaymentResponseActionOneOfInterface: (interface {}) <nil>
})
```

The API does return something like this for the request:

```json
  {
    "resultCode": "Pending",
    "action": {        
        "paymentData": "Ab0...",
        "paymentMethodType": "paypal",
        "sdkData": {
            "token": "EC-3.."
        },
        "type": "sdk"
    },
    "details": [
        {
            "key": "token",
            "type": "text"
        }
    ],
    "outputDetails": {
        "token": "EC-3.."
    },
    "paymentData": "Ab0...",
}
```

**To Reproduce**
```golang
	t.Run("Create a valid paypal Request", func(t *testing.T) {
		req := &checkout.PaymentRequest{
			Reference: "123456781235",
			Amount: checkout.Amount{
				Value:    1250,
				Currency: "EUR",
			},
			CountryCode:     "NL",
			MerchantAccount: MerchantAccount,
			Channel:         "Web",
			ReturnUrl:       "http://localhost:3000/redirect",
			PaymentMethod: map[string]interface{}{
				"subtype": "sdk",
				"type":    "paypal",
			},
		}

		require.Nil(t, req.ApplicationInfo)

		res, httpRes, err := client.Checkout.Payments(req)
		require.Nil(t, err)
		require.NotNil(t, httpRes)
		assert.Equal(t, 200, httpRes.StatusCode)
		require.NotNil(t, res)
		// @todo: validate real paypal response
		require.NotNil(t, res.Action.PaymentResponseActionOneOfInterface)
		require.NotNil(t, res.PaymentData)

		// check if req has ApplicationInfo added to it
		require.NotNil(t, req.ApplicationInfo)
		require.NotNil(t, req.ApplicationInfo.AdyenLibrary)
		require.Equal(t, common.LibName, req.ApplicationInfo.AdyenLibrary.Name)
		require.Equal(t, common.LibVersion, req.ApplicationInfo.AdyenLibrary.Version)
	})
```

**Expected behavior**
Give me back the actions from the api so I can handle it in the frontend

**Comment by steffenmllr** [comment]
Look like this might be related https://github.com/OpenAPITools/openapi-generator/issues/8086

It seems like this makes the `v4`release unusable, the payment action can not be processed on the frontend when it is always null.

Would be nice if someone could take a look at this.

**Comment by roybos** [comment]
I can confirm this issue.

When implementing the checkout with the DropIn, I didn't get the correct response. When I switched to V3 everything was working as it should. So this release is indeed unusable. It would also be wise to write proper tests to test res.Action as it is an important part of the payment flow. The current tests are only asserting `require.NotNil(t, res.Action)` which is pretty useless.

**Comment by mderasse** [comment]
Hi, any update regarding that issue and the PR (cc @KadoBOT) ?
Right now the v4 cannot be use

**Comment by deepu105** [comment]
@steffenmllr we still need to merge your PR, as the tests are failing need to check whats going on there. @mderasse we are on it, there are few other things we are trying to sort out. There should be a new release soon. thanks for the patience

**Comment by steffenmllr** [comment]
That would be great. Looks like they even solved this issue upstream: https://github.com/OpenAPITools/openapi-generator/issues/8086#issuecomment-757911778 - might be worth looking into it instead of solving this with my PR.

This library/release was now broken for 3 Months so another couple of days won't hurt anybody 😄
